version: "3.7"
services:
  store-api:
    container_name: sx-store-api
    image: store-api:latest
    restart: always
    environment:
      RUN_ENV: prod
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: sx-etcd-node1:2379,sx-etcd-node2:2379,sx-etcd-node3:2379
    networks:
      - sx-net
    extra_hosts:
      - minio.wemeng.com:172.18.0.19
networks:
  sx-net:
    external: true # 使用自定义创建好的网络，我创建的网络名加sx-net，方便与其他服务通信